blank_issues_enabled: true
contact_links:
  - name: ğŸ—’ï¸  nprintML README
    url: https://github.com/nprint/nprintML#readme
    about: Consult the nprintML README first.
  - name: ğŸ“– nprintML Wiki
    url: https://github.com/nprint/nprintML/wiki
    about: Learn more about how to use nprintML here.
  - name: ğŸ“– nPrint Wiki
    url: https://github.com/nprint/nprint/wiki
    about: Learn more about how to use nPrint here.
